
import { prisma } from '../src/lib/prisma';

async function main() {
    try {
        // 1. Get a category
        const category = await prisma.category.findFirst();
        if (!category) {
            console.error("No category found in DB. Cannot test product creation.");
            process.exit(1);
        }
        console.log(`Using category: ${category.name} (${category.id})`);

        // 2. Prepare payload
        const payload = {
            name: "Test Plant " + Date.now(),
            description: "A test plant generated by verification script",
            price: 99.99,
            stock: 100,
            categoryId: category.id,
            imageUrl: "https://example.com/plant.jpg",
            tags: ["test"]
        };

        // 3. Send Request
        const url = 'http://localhost:3001/api/products';
        console.log(`Sending POST to ${url}...`);

        try {
            const response = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(payload)
            });

            if (response.ok) {
                const data = await response.json();
                console.log("SUCCESS: Product created via API with auto-generated slug!");
                console.log("Product Slug:", data.slug);

                // Cleanup
                await prisma.product.delete({ where: { id: data.id } });
                console.log("Test product deleted from DB.");
            } else {
                console.error(`FAILED: API returned ${response.status}`);
                console.error(await response.text());
            }
        } catch (fetchError) {
            console.error("FAILED to connect to API. Is the server running on port 3001?");
            console.error("If the server is not running, please run 'npm run dev' in the server directory and try again, or manually verify the fix.");
        }

    } catch (e) {
        console.error("Script Error:", e);
    } finally {
        await prisma.$disconnect();
    }
}

main();
